{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "segway-sys-source-box-enterprise.secretname" . }}
  labels:
    {{- include "segway-sys-source-box-enterprise.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  "box.json": {{ index .Values "secret" "data" "box.json" | b64enc }}
{{- end }}
