apiVersion: v1
kind: Service
metadata:
  name: {{ include "segway-sys-source-ms-azure-eventhub.fullname" . }}
  labels:
    {{- include "segway-sys-source-ms-azure-eventhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "segway-sys-source-ms-azure-eventhub.selectorLabels" . | nindent 4 }}
